name: Deploy Coverage Report to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload coverage report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./coverage-report   # adjust path to your report folder

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Teams with report link
        run: |
          curl -H 'Content-Type: application/json' \
          -d "{\"text\":\"✅ Test Report is ready: ${{ steps.deployment.outputs.page_url }}\"}" \
          "https://prod-91.westus.logic.azure.com:443/workflows/3d1b0262a151447fa4af191b76e738ec/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=d3JmTZuACN80oOmIAtAYIp5HtaeBzw8R4EqQwJ9GX-Q"



      
        
